<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Iovista\ProductComment\Block\Product\Comment $block */
?>
<div id="product-comment-container" data-role="product-comment"></div>
<?= $block->getChildHtml() ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Iovista_ProductComment/js/process-reviews": {
                "productCommentUrl": "<?= $block->escapeJs($block->getProductReviewUrl()) ?>",
                "commentsTabSelector": "#tab-label-productComments"
            }
        }
    }
</script>
